TRUNCATE TABLE `mw_ep_orgs`;
TRUNCATE TABLE `mw_ep_courses`;
TRUNCATE TABLE `mw_ep_students`;
TRUNCATE TABLE `mw_ep_users_per_course`;
TRUNCATE TABLE `mw_ep_instructors`;
TRUNCATE TABLE `mw_ep_oas`;
TRUNCATE TABLE `mw_ep_cas`;
TRUNCATE TABLE `mw_ep_articles`;
TRUNCATE TABLE `mw_ep_revisions`;